config/routes.rb
Rails.application.routes.draw do
  # resources :reviews
  # resources :posts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "pages#index"

namespace :api do
  namespace :v1 do
    resources :posts, param: :slug
    resources :reviews, only: [:create, :destroy, :index] 
  end
end

get "*path", to: "pages#index", via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reviews

  before_create :slugify

  def slugify
    self.slug = title.parameterize
  end

  def avg_score
    return 0 unless reviews.count.positive?

    reviews.average(:score).round(2).to_f
  end
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      skip_before_action :verify_authenticity_token
      # before_action :set_post, only: [:show, :edit, :update, :destroy]
      
      protect_from_forgery with: :null_session
      

      # GET /posts
      # GET /posts.json
      def index
        posts = Post.all

        render json: PostSerializer.new(posts, options).serialized_json
      end

      # GET /posts/1
      # GET /posts/1.json
      def show
        post = Post.find_by(slug: params[:slug])

        render json: PostSerializer.new(post, options).serialized_json
      end

      # GET /posts/new
      def new
        post = Post.new
      end

      # GET /posts/1/edit
      def edit
      end

      # POST /posts
      # POST /posts.json
      def create
        post = Post.new(post_params)
        
        # post.user = current_user

        
          if post.save
            render json: PostSerializer.new(post).serialized_json
          else
            render json: { error: post.errors.messages }, status: 422
          end
        
      end

      # PATCH/PUT /posts/1
      # PATCH/PUT /posts/1.json
      def update
        post = Post.find_by(slug: params[:slug])

        
          if post.update(post_params)
            render json: PostSerializer.new(post, options).serialized_json
          else
            render json: { error: post.errors.messages }, status: 422
          
          end
      end

      # DELETE /posts/1
      # DELETE /posts/1.json
      def destroy
        post = Post.find_by(slug: params[:slug])
        
        if post.destroy
          head :no_content
        else
          render json: { error: post.errors.messages }, status: 422
        end
        
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = Post.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def post_params
          params.require(:post).permit(:title, :url, :code, :slug, :user_id)
        end

        def options
          @options ||= { include: %i[reviews]}
        end
               
        def current_user
          return unless session[:user_id]
          current_user ||= User.find(session[:user_id])
        end

        def logged_in?
          !!session[:user_id]
        end


    end
  end
end

app/controllers/api/v1/reviews_controller.rb
module Api
  module V1
    class ReviewsController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :set_review, only: [:show, :edit, :update, :destroy]

      protect_from_forgery with: :null_session

      # GET /reviews
      # GET /reviews.json
      def index
        reviews = Review.all

        render json: ReviewSerializer.new(reviews).serialized_json
      end

      # GET /reviews/1
      # GET /reviews/1.json
      def show
      end

      # GET /reviews/new
      def new
        @review = Review.new
      end

      # GET /reviews/1/edit
      def edit
      end

      # POST /reviews
      # POST /reviews.json
      def create
        review = post.reviews.new(review_params)

        # review.user = current_user

          if review.save
            render json: ReviewSerializer.new(review).serialized_json
          else
            render json: { error: review.errors.messages }, status: 422
          
        end
      end

      # PATCH/PUT /reviews/1
      # PATCH/PUT /reviews/1.json
      def update
        respond_to do |format|
          if @review.update(review_params)
            format.html { redirect_to @review, notice: 'Review was successfully updated.' }
            format.json { render :show, status: :ok, location: @review }
          else
            format.html { render :edit }
            format.json { render json: @review.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /reviews/1
      # DELETE /reviews/1.json
      def destroy
        review = Review.find(params[:id])
        
        if review.destroy
          head :no_content
        else
          render json: { error: review.errors.messages }, status: 422
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_review
          @review = Review.find(params[:id])
        end

        def post
            @post ||= Post.find(params[:post_id])
        end

        # Only allow a list of trusted parameters through.
        def review_params
          params.require(:review).permit(:title, :description, :score, :user_id, :post_id)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project4DesignSharingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= javascript_pack_tag 'index' %>
<%= stylesheet_pack_tag 'application' %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_area :code %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Code</th>
      <th>Slug</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.code %></td>
        <td><%= post.slug %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Code:</strong>
  <%= @post.code %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Score</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.description %></td>
        <td><%= review.score %></td>
        <td><%= review.user_id %></td>
        <td><%= review.post_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<p>
  <strong>Score:</strong>
  <%= @review.score %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @review.post_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>